# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
    secret_key_base: e839e2cc3c9e9977b5765bd3dfcabcc944c33a4d5776a58d32b2150e760b22a9649eeba7dd25e7aff50d76218b66bb48e98823e66b6732e0f6546caf34bec27a
    github_client_id: cd6043da7e36213f25b2
    github_client_secret: d811d3324f45fbb6364864e847ec793e870d45ce

test:
    secret_key_base: 8773c1ca845f1512dcbb6fdc2956eb1b87b053c563a3279dfaf74e82ed1cd481ee3949cbd4f1ebda087fffa4fafa98315507f1e4dfb9b1619d30fd52cf8a7e3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>